[package]
name = "databend-common-sql"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = true

[features]
default = []
storage-hdfs = ["databend-common-config/storage-hdfs"]

[dependencies]
ahash = { version = "0.8.2", features = ["no-rng"] }
anyhow = { workspace = true }
async-backtrace = { workspace = true }
async-recursion = "1.1.1"
async-trait = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
cidr = { version = "0.2.2" }
cron = "0.12.0"
ctor = { workspace = true }
dashmap = { workspace = true }
databend-common-ast = { workspace = true }
databend-common-async-functions = { workspace = true }
databend-common-base = { workspace = true }
databend-common-catalog = { workspace = true }
databend-common-compress = { workspace = true }
databend-common-config = { workspace = true }
databend-common-exception = { workspace = true }
databend-common-expression = { workspace = true }
databend-common-functions = { workspace = true }
databend-common-license = { workspace = true }
databend-common-meta-app = { workspace = true }
databend-common-meta-types = { workspace = true }
databend-common-metrics = { workspace = true }
databend-common-pipeline-core = { workspace = true }
databend-common-pipeline-transforms = { workspace = true }
databend-common-settings = { workspace = true }
databend-common-storage = { workspace = true }
databend-common-storages-result-cache = { workspace = true }
databend-common-sharing = { workspace = true }
databend-common-storages-view = { workspace = true }
databend-common-users = { workspace = true }
databend-enterprise-data-mask-feature = { workspace = true }
databend-storages-common-table-meta = { workspace = true }
derive-visitor = { workspace = true }
educe = "0.4"
enum-as-inner = "0.5"
globiter = "0.1"
indexmap = "2.0.0"
itertools = { workspace = true }
jsonb = { workspace = true }
log = { workspace = true }
minitrace = { workspace = true }
num-derive = "0.3.3"
num-traits = "0.2.15"
opendal = { workspace = true }
ordered-float = { workspace = true }
parking_lot = { workspace = true }
percent-encoding = "2"
prqlc = "0.11.3"
recursive = "0.1.1"
regex = { workspace = true }
roaring = "0.10.1"
serde = { workspace = true }
simsearch = "0.2"
time = "0.3.14"
url = "2.3.1"

[lints]
workspace = true
