[package]
name = "common-sql"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
default = []

z3-prove = ["common-constraint", "z3"]

[dependencies] # In alphabetical order
# Workspace dependencies
common-ast = { path = "../ast" }
common-base = { path = "../../common/base" }
common-catalog = { path = "../catalog" }
common-config = { path = "../config" }
common-constraint = { path = "../constraint", optional = true }
common-exception = { path = "../../common/exception" }
common-expression = { path = "../expression" }
common-functions = { path = "../functions" }
common-license = { path = "../../common/license" }
common-meta-app = { path = "../../meta/app" }
common-meta-types = { path = "../../meta/types" }
common-profile = { path = "../../common/profile" }

common-pipeline-core = { path = "../pipeline/core" }
common-pipeline-sources = { path = "../pipeline/sources" }
common-pipeline-transforms = { path = "../pipeline/transforms" }

common-settings = { path = "../settings" }
common-storage = { path = "../../common/storage" }
common-storages-parquet = { path = "../storages/parquet" }
common-storages-result-cache = { path = "../storages/result_cache" }
common-storages-view = { path = "../storages/view" }
common-users = { path = "../users" }
storages-common-table-meta = { path = "../storages/common/table-meta" }
data-mask-feature = { path = "../ee-features/data-mask" }

# GitHub dependencies

# Crates.io dependencies
ahash = { version = "0.8.2", features = ["no-rng"] }
anyhow = { workspace = true }
async-backtrace = { workspace = true }
async-recursion = "1.0.0"
async-trait = { version = "0.1.57", package = "async-trait-fn" }
chrono = { workspace = true }
chrono-tz = { workspace = true }
ctor = "0.1.26"
dashmap = "5.4"
educe = "0.4"
enum-as-inner = "0.5"
globiter = "0.1"
itertools = "0.10.5"
num-derive = "0.3.3"
num-traits = "0.2.15"
once_cell = "1.15.0"
opendal = { workspace = true }
ordered-float = { workspace = true }
parking_lot = "0.12.1"
percent-encoding = "2"
regex = "1.8.1"
roaring = "0.10.1"
serde = { workspace = true }
simsearch = "0.2"
time = "0.3.14"
tracing = "0.1.36"
url = { version = "2.3" }
z3 = { version = "0.11.2", features = ["static-link-z3"], optional = true }
