[package]
name = "common-meta-app"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
common-datavalues = { path = "../../query/datavalues" }
common-meta-types = { path = "../types" }
common-storage = { path = "../../common/storage" }
common-exception = { path = "../../common/exception" }

chrono = { workspace = true }
enumflags2 = { version = "0.7.5", features = ["serde"] }
maplit = "1.0.2"
num-derive = "0.3.3"
num-traits = "0.2.15"
serde = { workspace = true }

[build-dependencies]
common-building = { path = "../../common/building" }
tonic-build = "0.8.0"
