[package]
name = "data-mask-feature"
description = "data mask"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
common-base = { path = "../../../common/base" }
common-exception = { path = "../../../common/exception" }
common-meta-app = { path = "../../../meta/app" }
common-meta-store = { path = "../../../meta/store" }

async-trait = "0.1.57"

[build-dependencies]

[package.metadata.cargo-machete]
ignored = ["match-template"]
