[package]
name = "databend-binaries"
description = "databend command line tools"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[features]
default = ["simd", "jemalloc", "z3-prove"]
memory-profiling = [
    "databend-meta/memory-profiling",
    "databend-query/memory-profiling",
    "databend-common-base/memory-profiling",
]
simd = ["databend-meta/simd", "databend-query/simd"]
z3-prove = ["databend-query/z3-prove"]
jemalloc = ["databend-common-base/jemalloc"]
io-uring = [
    "databend-meta/io-uring",
    "databend-query/io-uring",
    "databend-common-meta-store/io-uring",
    "databend-common-meta-sled-store/io-uring",
    "databend-common-meta-raft-store/io-uring",
]

[dependencies]
# Workspace dependencies
databend-common-base = { path = "../common/base" }
databend-common-config = { path = "../query/config" }
databend-common-exception = { path = "../common/exception" }
databend-common-grpc = { path = "../common/grpc" }
databend-common-license = { path = "../common/license" }
databend-common-meta-api = { path = "../meta/api" }
databend-common-meta-app = { path = "../meta/app" }
databend-common-meta-client = { path = "../meta/client" }
databend-common-meta-kvapi = { path = "../meta/kvapi" }
databend-common-meta-raft-store = { path = "../meta/raft-store" }
databend-common-meta-sled-store = { path = "../meta/sled-store" }
databend-common-meta-store = { path = "../meta/store" }
databend-common-meta-types = { path = "../meta/types" }
databend-common-metrics = { path = "../common/metrics" }
databend-common-storage = { path = "../common/storage" }
databend-common-tracing = { path = "../common/tracing" }
databend-enterprise-query = { path = "../query/ee" }
databend-meta = { path = "../meta/service" }
databend-query = { path = "../query/service" }
# databend-enterprise-meta = { path = "../meta/ee" }
databend-enterprise-background-service = { path = "../query/ee_features/background_service" }
databend-sharing-endpoint = { path = "../query/sharing_endpoint" }
databend-storages-common-table-meta = { path = "../query/storages/common/table_meta" }
# Crates.io dependencies
anyerror = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
limits-rs = "0.2.0"
log = { workspace = true }
minitrace = { workspace = true }
opendal = { workspace = true }
poem = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serfig = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }

url = "2.3.1"

[[bin]]
name = "databend-meta"
path = "meta/ee_main.rs"
doctest = false
test = false

[[bin]]
name = "databend-meta-oss"
path = "meta/oss_main.rs"
doctest = false
test = false

[[bin]]
name = "databend-metabench"
path = "metabench/main.rs"
doctest = false
test = false

[[bin]]
name = "databend-metactl"
path = "metactl/main.rs"
doctest = false
test = false

[[bin]]
name = "databend-metaverifier"
path = "metaverifier/main.rs"
doctest = false
test = false

[[bin]]
name = "databend-query"
path = "query/ee_main.rs"
doctest = false
test = false

[[bin]]
name = "databend-query-oss"
path = "query/oss_main.rs"
doctest = false
test = false

[[bin]]
name = "open-sharing"
path = "opensharing/main.rs"
doctest = false
test = false

[[bin]]
name = "table-meta-inspector"
path = "tool/table_meta_inspector.rs"
doctest = false
test = false
