[package]
name = "enterprise-query"
description = "A real-time Cloud Distributed Query Engine"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
aggregating-index = { path = "../ee-features/aggregating-index" }
async-backtrace = { workspace = true }
common-base = { path = "../../common/base" }
common-catalog = { path = "../catalog" }
common-config = { path = "../config" }
common-exception = { path = "../../common/exception" }
common-license = { path = "../../common/license" }
common-meta-api = { path = "../../meta/api" }
common-meta-app = { path = "../../meta/app" }
common-meta-kvapi = { path = "../../meta/kvapi" }
common-meta-store = { path = "../../meta/store" }
common-meta-types = { path = "../../meta/types" }
common-settings = { path = "../../query/settings" }
common-sql = { path = "../sql" }
common-storages-fuse = { path = "../storages/fuse" }
common-users = { path = "../users" }
data-mask-feature = { path = "../ee-features/data-mask" }
databend-query = { path = "../service" }
storages-common-cache = { path = "../storages/common/cache" }
storages-common-table-meta = { path = "../storages/common/table-meta" }
table-lock = { path = "../ee-features/table-lock" }
vacuum-handler = { path = "../ee-features/vacuum-handler" }

async-trait = "0.1.57"
chrono = { workspace = true }
dashmap = "5.4"
futures-util = "0.3.24"
jwt-simple = "0.11.0"
tracing = "0.1.36"

[build-dependencies]
common-building = { path = "../../common/building" }

[package.metadata.cargo-machete]
ignored = ["match-template"]
